env:
  jest: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:@vitest/legacy-recommended
  - plugin:prettier/recommended
rules:
  import/no-unresolved:
    - error
    -
      ignore: ['^vitest/config']
